#!/usr/bin/env python3
"""Create a pull request for the AI-generated fix branch."""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Any


class PullRequestError(RuntimeError):
    """Raised when PR creation fails."""


def log(level: str, message: str, **fields: Any) -> None:
    """Print structured logs for GitHub Actions."""
    payload = {"level": level, "message": message, **fields}
    stream = sys.stderr if level == "ERROR" else sys.stdout
    print(json.dumps(payload, sort_keys=True), file=stream)


def read_json(path: Path) -> dict[str, Any]:
    """Read a JSON object from disk."""
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise PullRequestError(f"Missing required file: {path}") from exc
    except json.JSONDecodeError as exc:
        raise PullRequestError(f"Invalid JSON in {path}: {exc}") from exc
    if not isinstance(data, dict):
        raise PullRequestError(f"{path} must contain a JSON object.")
    return data


def run_gh(args: list[str], cwd: Path | None = None, check: bool = True) -> subprocess.CompletedProcess[str]:
    """Run a GitHub CLI command with captured output."""
    env = os.environ.copy()
    if not env.get("GH_TOKEN") and env.get("GITHUB_TOKEN"):
        env["GH_TOKEN"] = env["GITHUB_TOKEN"]

    result = subprocess.run(
        ["gh", *args],
        cwd=cwd,
        env=env,
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if check and result.returncode != 0:
        raise PullRequestError(
            f"gh {' '.join(args[:2])} failed with exit {result.returncode}: "
            f"{(result.stderr or result.stdout).strip()}"
        )
    return result


def detect_base_branch(target_repo: Path) -> str:
    """Use the target repo default branch if available; otherwise fall back to main."""
    result = subprocess.run(
        ["git", "symbolic-ref", "--short", "refs/remotes/origin/HEAD"],
        cwd=target_repo,
        check=False,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    ref = result.stdout.strip()
    if result.returncode == 0 and ref.startswith("origin/"):
        return ref.removeprefix("origin/")
    return "main"


def build_pr_body(parsed_issue: dict[str, Any], git_result: dict[str, Any]) -> str:
    """Build a review-friendly pull request body."""
    issue_number = parsed_issue["issue_number"]
    issue_title = parsed_issue["issue_title"]
    modified_files = git_result.get("modified_files", [])
    modified_list = "\n".join(f"- `{filename}`" for filename in modified_files) or "- None recorded"

    return f"""## AI-generated fix

This pull request was generated automatically from issue #{issue_number}.

## Source issue

- Issue number: #{issue_number}
- Issue title: {issue_title}

## Modified files

{modified_list}

## Human review required

This change was generated by Claude and committed by GitHub Actions. Please review the code, run the relevant tests, and confirm the behaviour before merging.
"""


def write_pr_result(path: Path, payload: dict[str, Any]) -> None:
    """Persist the PR URL for the issue-comment step."""
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def main() -> int:
    """Create or discover a PR for the pushed branch."""
    try:
        if not (os.getenv("GH_TOKEN") or os.getenv("GITHUB_TOKEN")):
            raise PullRequestError("Missing GH_TOKEN or GITHUB_TOKEN for GitHub CLI.")

        parsed_issue = read_json(Path("parsed_issue.json"))
        git_result = read_json(Path("git_result.json"))
        target_repo = Path("target-repo")
        repo_owner = git_result["repo_owner"]
        repo_name = git_result["repo_name"]
        repo_full_name = f"{repo_owner}/{repo_name}"
        branch_name = git_result["branch_name"]
        base_branch = detect_base_branch(target_repo)
        title = f"AI Fix: {parsed_issue['issue_title']}"
        body = build_pr_body(parsed_issue, git_result)

        # If a retry reruns the workflow for the same branch, reuse the existing PR.
        existing = run_gh(
            ["pr", "view", branch_name, "--repo", repo_full_name, "--json", "url", "--jq", ".url"],
            cwd=target_repo,
            check=False,
        )
        if existing.returncode == 0 and existing.stdout.strip():
            pr_url = existing.stdout.strip()
            log("INFO", "Existing pull request found", pr_url=pr_url)
        else:
            created = run_gh(
                [
                    "pr",
                    "create",
                    "--repo",
                    repo_full_name,
                    "--head",
                    branch_name,
                    "--base",
                    base_branch,
                    "--title",
                    title,
                    "--body",
                    body,
                ],
                cwd=target_repo,
            )
            pr_url = created.stdout.strip().splitlines()[-1]
            if not pr_url.startswith("https://"):
                raise PullRequestError(f"Could not parse PR URL from gh output: {created.stdout!r}")
            log("INFO", "Pull request created", pr_url=pr_url, base=base_branch, head=branch_name)

        write_pr_result(
            Path("pr_result.json"),
            {
                "repo_owner": repo_owner,
                "repo_name": repo_name,
                "branch_name": branch_name,
                "base_branch": base_branch,
                "pr_url": pr_url,
                "modified_files": git_result.get("modified_files", []),
            },
        )
        return 0
    except PullRequestError as exc:
        log("ERROR", "Pull request creation failed", error=str(exc))
        return 1


if __name__ == "__main__":
    sys.exit(main())
